[package]
name = "mimc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
num-bigint = "0.4.4"
wasm-bindgen = "0.2.83"
